apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-tunnel-texasdust-org
  namespace: cloudflared
spec:
  itemPath: vaults/mbn7rk3d5gfgofrv3a2zt2tdoe/items/cloudflare-tunnel-texasdust-org
